### ISSUE TITLE
No such file or directory: 'data/database/ut-zappos.t7'

### ISSUE THREAD

**Issue by PanXGzhu** [jingchenchen/RAPR#1]
![image](https://github.com/user-attachments/assets/236fc85a-b574-4ed6-98cf-dafbedfea496)

I saw you said you put the databases for each dataset are in the directory of "data/database", but sorry,  I can't find it location.... Is it need me  download when i download the dataset?

**Comment by jingchenchen** [comment]
The databses have been uploaded. Sorry for the mistake.

**Comment by PanXGzhu** [comment]
thank you!
